### ISSUE TITLE
problem with python and homebrew

### ISSUE THREAD

**Issue by iltommi** [aurelien-rainone/macdeployqtfix#1]
HI,
thanks for your code, it saved my life!
I stll have something weird happening with my code.

The code (https://github.com/aflux/neutrino/) links on libPythonQt  (http://pythonqt.sourceforge.net/) which links on Python.
I installed homebrew and compiled pythonqt by hand 
Then I compile my code and run both macdeployqt and macdeployqtfix.py and everything is fine except the Python framework linked by pythonqt 
As you can see the dependencies of both Pythonqt libs are still pointing to /usr/local/Frameworks (although Python Frameworks get copied in my .app)
It should be macdeployqt job to fix this, but it seems it has a lot of problems....

I ended up fixing this with install_name_tool, but I was wondering if it was possible to add a hook to your script to fix this issue too.

many thanks!

---

These are the dependencies of Pytohnqt:

```
otool -L lib/libPythonQt.dylib 
lib/libPythonQt.dylib:
    libPythonQt.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/local/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
    /usr/local/opt/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.5.0, current version 5.5.0)
    /usr/local/opt/qt5/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.5.0, current version 5.5.0)
    /usr/local/opt/qt5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.5.0, current version 5.5.0)
    /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
    /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
    /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
    /System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

otool -L lib/libPythonQt_QtAll.dylib 
lib/libPythonQt_QtAll.dylib:
    libPythonQt_QtAll.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/local/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
    libPythonQt.1.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/local/opt/qt5/lib/QtWebKitWidgets.framework/Versions/5/QtWebKitWidgets (compatibility version 5.5.0, current version 5.5.0)
    /usr/local/opt/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.5.0, current version 5.5.0)
    /usr/local/opt/qt5/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.5.0, current version 5.5.0)
    /usr/local/opt/qt5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.5.0, current version 5.5.0)
    /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
    /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
    /usr/local/opt/qt5/lib/QtWebKit.framework/Versions/5/QtWebKit (compatibility version 5.5.0, current version 5.5.0)
    /usr/local/opt/qt5/lib/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.5.0, current version 5.5.0)
    /usr/local/opt/qt5/lib/QtSvg.framework/Versions/5/QtSvg (compatibility version 5.5.0, current version 5.5.0)
    /usr/local/opt/qt5/lib/QtOpenGL.framework/Versions/5/QtOpenGL (compatibility version 5.5.0, current version 5.5.0)
    /usr/local/opt/qt5/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (compatibility version 5.5.0, current version 5.5.0)
    /usr/local/opt/qt5/lib/QtMultimediaWidgets.framework/Versions/5/QtMultimediaWidgets (compatibility version 5.5.0, current version 5.5.0)
    /usr/local/opt/qt5/lib/QtMultimedia.framework/Versions/5/QtMultimedia (compatibility version 5.5.0, current version 5.5.0)
    /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
    /System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
    /usr/local/opt/qt5/lib/QtXmlPatterns.framework/Versions/5/QtXmlPatterns (compatibility version 5.5.0, current version 5.5.0)
    /usr/local/opt/qt5/lib/QtSql.framework/Versions/5/QtSql (compatibility version 5.5.0, current version 5.5.0)
    /usr/local/opt/qt5/lib/QtXml.framework/Versions/5/QtXml (compatibility version 5.5.0, current version 5.5.0)
    /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

**Comment by arl** [comment]
Hi @iltommi, happy to hear that macdeployqtfix is useful for you.

It should be easy to extend `macdeployqtfix` so that it copies and corrects every shared library found in the bundle, provided that those paths are paths of Qt libraries.

So for your specific case, the Qt libraries on which `libPythonQt.dylib` and `libPythonQt_QtAll.dylib`  depend would be copied (if needed), and their rpath corrected, etc.

I'll do it when i have a bit of time...
Stay tuned :wink:

**Comment by tresf** [comment]
This seems to be happening for me with some Homebrew-specific libraries that the original `macdeployqt` fails to copy.  Can the tool be run against a non-qt prefix?

Furthermore, [QtXml seems to be having a linking issue as well, requiring a subsequent run of the tool](https://github.com/LMMS/lmms/issues/2862#issuecomment-227307119).

**Comment by iltommi** [comment]
@tresf  made some fixing check the latest version. I'm closing the issue. 

If you still have problems, maybe it's better to open another issue

**Comment by tresf** [comment]
> @tresf *I made some fixing check the latest version. I'm closing the issue.

**Edit:** Thanks, the fix I had employed (not `macdeployqtfix` related) was to roll our project's Homebrew back to Qt 5.5, using `brew install qt55` since the underlying linking bugs in Qt 5.6.1 seemed to be the major cause of our project's linking issues.  Once this was done, we removed `macdeployqtfix` from our source tree and used the built-in linking utility combined with some of our existing `install_name_tool` post-build tasks.  So the issues is closed for me as well, albeit indirectly.

**Comment by tresf** [comment]
> @tresf *I made some fixing check the latest version. I'm closing the issue.

Disregard my previous comment.  I understand the context of your comment now.

**Comment by arl** [comment]
Ok thanks for the clarification
Le 7 juil. 2016 20:23, "Tres Finocchiaro" notifications@github.com a
écrit :

**Comment by iltommi** [comment]
Well I don't know, but the problem with the library `pythonqt` has gone. I now build that library using cmake rather than qmake and since my program uses the same build-system, I suspect things got somehow harmonised.
