### ISSUE TITLE
Nothing done for libraries [fixed]

### ISSUE THREAD

**Issue by MichaelVoelkel** [aurelien-rainone/macdeployqtfix#10]
Hi,

the dependencies that the tool mainly finds start like `@rpath/QtWidgets.framework/Versions/5/QtWidgets`

However, they are not recognized by the tool to be a lib, so nothing happens.

The tool will add all platform files etc., but no lib, which is why the app will not start afterwards with the crash message that the library QtWidgets could not be found. Any ideas?

Edit:
Okay, it seemed that there was some error in `macdeployqt` already which lied in differing versions of Xcode and install_name_tool. The latter comes from command line tools, which need to be exactly the same as the ones of Xcode. Command line tools can be found here: https://developer.apple.com/download

Then, `macdeployqt` will have fewer errors and `macdeployqtfix` can do its job. Thank you for this great tool!

**Comment by arl** [comment]
:D thanks
