### ISSUE TITLE
Doesn't work on Python 3.12

### ISSUE THREAD

**Issue by vadi2** [aurelien-rainone/macdeployqtfix#12]
The script seems to fail running on Python 3.12:

```
Traceback (most recent call last):
  File "/Users/runner/work/Mudlet/b/ninja/macdeployqtfix.py", line 394, in <module>
    main()
  File "/Users/runner/work/Mudlet/b/ninja/macdeployqtfix.py", line 384, in main
    if fix_main_binaries():
       ^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/Mudlet/b/ninja/macdeployqtfix.py", line 322, in fix_main_binaries
    if fix_binary(GlobalConfig.exepath):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/Mudlet/b/ninja/macdeployqtfix.py", line 306, in fix_binary
    for dep in get_dependencies(binary):
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/Mudlet/b/ninja/macdeployqtfix.py", line 63, in get_dependencies
    deps = [s.strip().split(' ')[0] for s in proc_out.stdout.splitlines()[1:] if s]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/Mudlet/b/ninja/macdeployqtfix.py", line 63, in <listcomp>
    deps = [s.strip().split(' ')[0] for s in proc_out.stdout.splitlines()[1:] if s]
            ^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
Error: Process completed with exit code 1.
```

**Comment by arl** [comment]
Thanks for reporting. However this project was developed at a time where python3 was not the norm, so it's probably not compatible, though I'm sure this would be a quick fix. I'm not using a Mac anymore though.

Also I'd have hoped that 8 years later, there wouldn't be the need to use it anymore (i.e. that macdeployqt would just do its job correctly 😝 )

**Comment by vadi2** [comment]
https://github.com/tamlok/macdeployqtfix/commit/390666219c004cfcee3bb7ddf00ca8980701b992 seems to be a fix!

**Comment by arl** [comment]
Oh that's nice.I'd gladly accept a PR, if you confirm it works on your Mac ;-)

**Comment by rparet** [comment]
I've put the fix for this in https://github.com/arl/macdeployqtfix/pull/13 
It's set to draft right now because I have a few other moving pieces to support amd64 osx builds for https://github.com/Mudlet/Mudlet

Let me know if it looks good and I'll set it to review.

**Comment by arl** [comment]
Closing since #13 is now merged!
