### ISSUE TITLE
Does not copy PlugIns

### ISSUE THREAD

**Issue by stonerl** [aurelien-rainone/macdeployqtfix#2]
Hi,

first of all thank you for this nifty script. One problem I have, though. It does not copy the PlugIns/platforms libs. And get this error:

```
This application failed to start because it could not find or load the Qt platform plugin "cocoa".
Reinstalling the application may fix this problem. The program has unexpectedly finished.
```

**Comment by arl** [comment]
Hi Tony,
i just corrected a mistake of mine in the README, i had wrongly written to use macdeployqtfix before running macdeployqt.

It should be the other way round, run macdeployqt to create the bundle and then macdeployqtfix. Could it be that?
If that's not the case, could you run `macdeployqtfix` with `-v` option and post the complete log here?
Thanks

**Comment by stonerl** [comment]
Applying the commands in the correct order solved it, thanks allot. And once again, thank you very much for this script. Time and headache saver. :smile:

**Comment by arl** [comment]
Great!
Happy that my script saves not only my time, but yours
